# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: neddykun <neddykun@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/07/06 11:02:52 by neddykun          #+#    #+#              #
#    Updated: 2026/07/06 11:02:52 by neddykun         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# PT: Compilador C++ usado no tester.
# EN: C++ compiler used by the tester.
CXX=c++
CXXFLAGS=-std=c++17 -Wall -Wextra -Werror
LDFLAGS=-Wl,--wrap=malloc

.DEFAULT_GOAL := all
MAKEFLAGS += --no-print-directory

# PT: Caminhos base do projeto e do tester.
# EN: Base paths for the project and the tester.
ROOT_DIR=..
SRC_DIR=src
INC_DIR=include
BUILD_DIR=build
NAME=libft_tester
LIBFT=$(ROOT_DIR)/libft.a
ARGS=

SRCS=$(wildcard $(SRC_DIR)/*.cpp)
OBJS=$(SRCS:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)

# PT: Garante que a biblioteca principal existe antes de ligar o tester.
# EN: Ensures the main library exists before linking the tester.
$(LIBFT):
	@$(MAKE) -s -C $(ROOT_DIR)

# PT: Cria a pasta onde ficam os objetos do tester.
# EN: Creates the folder where the tester objects are stored.
$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

# PT: Compila um objeto C++ a partir do ficheiro fonte correspondente.
# EN: Compiles one C++ object from its matching source file.
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp $(INC_DIR)/tester.hpp $(INC_DIR)/test_modules.hpp $(INC_DIR)/malloc_fail.hpp $(LIBFT) | $(BUILD_DIR)
	@$(CXX) $(CXXFLAGS) -I$(INC_DIR) -I$(ROOT_DIR) -c $< -o $@

# PT: Liga o executavel final do tester.
#     O wrap do malloc deixa o tester simular falhas de alocacao.
# EN: Links the final tester executable.
#     The malloc wrap lets the tester simulate allocation failures.
$(NAME): $(OBJS)
	@$(CXX) $(CXXFLAGS) $^ $(LIBFT) $(LDFLAGS) -o $@

# PT: Compila o tester e corre a suite toda.
# EN: Builds the tester and runs the full suite.
all: $(NAME)
	@./$(NAME) $(ARGS)

# PT: Mostra a ajuda do tester.
# EN: Shows the tester help message.
help: $(NAME)
	@./$(NAME) --help

# PT: Corre a suite sem recompilar se o binario ja existir.
# EN: Runs the suite without recompiling if the binary already exists.
run: $(NAME)
	@./$(NAME) $(ARGS)

# PT: Mostra as suites e funcoes conhecidas.
# EN: Shows the known suites and functions.
list: $(NAME)
	@./$(NAME) --list

# PT: Corre sem agregar os estados dos testes.
# EN: Runs without aggregating test statuses.
verbose: $(NAME)
	@./$(NAME) --verbose $(ARGS)

# PT: Produz output JSON para scripts e CI.
# EN: Produces JSON output for scripts and CI.
json: $(NAME)
	@./$(NAME) --json $(ARGS)

# PT: Output estavel para CI: JSON e sem cores.
# EN: Stable CI output: JSON and no colors.
ci: $(NAME)
	@./$(NAME) --json --no-color $(ARGS)

# PT: Corre com Valgrind para apanhar leaks e acessos invalidos.
# EN: Runs with Valgrind to catch leaks and invalid memory accesses.
leaks: $(NAME)
	@LIBFT_TESTER_NO_FORK=1 valgrind --leak-check=full \
		--show-leak-kinds=all --track-origins=yes \
		--errors-for-leak-kinds=all --error-exitcode=42 ./$(NAME) $(ARGS); \
		exit $$?

# PT: Remove os objetos e o executavel do tester.
# EN: Removes the tester objects and executable.
clean:
	@rm -rf $(BUILD_DIR) $(NAME)

# PT: Remove tudo o que o tester gerou.
# EN: Removes everything generated by the tester.
fclean: clean
	@$(MAKE) -s -C $(ROOT_DIR) fclean

# PT: Reconstroi tudo do zero.
# EN: Rebuilds everything from scratch.
re: fclean all

# PT: Alvos que nao criam ficheiros.
# EN: Targets that do not create files.
.PHONY: all help run list verbose json ci leaks clean fclean re
